@AgentLab.Api_HostAddress = http://localhost:5030

POST {{AgentLab.Api_HostAddress}}/api/simple-chat
Accept: application/json
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Where do I store my OpenAI API key?"
    }
  ]
}
